#!/usr/bin/env node
// Build-time catalog generator.
//
// 1. Reads public/animals/world-map.json (master list).
// 2. For each animal, ensures public/animals/<slug>.svg exists; if missing,
//    downloads it from the OpenMoji GitHub raw CDN using the codepoint.
// 3. Emits src/data/animals.js — a per-world, per-letter pool the runtime
//    can import directly. Letters with no animal in a world are omitted.
// 4. Prints a coverage report (letters covered per world).
//
// Safe to run repeatedly. Failed downloads are logged but not fatal; the
// catalog simply omits the missing animals.

import { promises as fs } from 'node:fs';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ANIMALS_DIR = join(ROOT, 'public', 'animals');
const WORLD_MAP_PATH = join(ANIMALS_DIR, 'world-map.json');
const OUTPUT_PATH = join(ROOT, 'src', 'data', 'animals.js');

const WORLDS = ['jungle', 'ocean', 'farm'];
const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

const OPENMOJI_BASE = 'https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/';

async function downloadIfMissing(slug, codepoint) {
  const path = join(ANIMALS_DIR, `${slug}.svg`);
  if (existsSync(path)) return { ok: true, cached: true };
  const url = `${OPENMOJI_BASE}${codepoint}.svg`;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      return { ok: false, error: `HTTP ${res.status}` };
    }
    const body = await res.text();
    if (!body.includes('<svg')) {
      return { ok: false, error: 'Not an SVG' };
    }
    await fs.writeFile(path, body, 'utf8');
    return { ok: true, cached: false };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

function letterOf(name) {
  return name.trim().charAt(0).toUpperCase();
}

function buildCatalog(animals) {
  // catalog[world][LETTER] = [{ slug, name }, ...]
  const catalog = Object.fromEntries(WORLDS.map((w) => [w, {}]));
  for (const a of animals) {
    const letter = letterOf(a.name);
    for (const world of a.worlds) {
      if (!catalog[world]) continue;
      (catalog[world][letter] ||= []).push({ slug: a.slug, name: a.name });
    }
  }
  return catalog;
}

function reportCoverage(catalog) {
  for (const world of WORLDS) {
    const lettersCovered = LETTERS.filter((L) => catalog[world][L]?.length);
    const totalAnimals = LETTERS.reduce(
      (sum, L) => sum + (catalog[world][L]?.length || 0),
      0,
    );
    console.log(
      `  ${world.padEnd(7)}: ${lettersCovered.length}/26 letters, ${totalAnimals} animals` +
        ` (missing: ${LETTERS.filter((L) => !catalog[world][L]?.length).join('') || 'none'})`,
    );
  }
}

function emitModule(catalog, animals) {
  const allBySlug = Object.fromEntries(animals.map((a) => [a.slug, { slug: a.slug, name: a.name }]));
  const body = `// AUTO-GENERATED by scripts/build-catalog.js. Do not edit by hand.
// Regenerate: \`npm run catalog\` (also runs automatically on dev/build).

export const WORLDS = ${JSON.stringify(WORLDS)};

export const CATALOG = ${JSON.stringify(catalog, null, 2)};

export const ALL_ANIMALS = ${JSON.stringify(allBySlug, null, 2)};
`;
  return body;
}

async function main() {
  console.log('Animal Keys — catalog build');

  const raw = JSON.parse(await fs.readFile(WORLD_MAP_PATH, 'utf8'));
  const animals = raw.animals;
  console.log(`  ${animals.length} animals in world-map.json`);

  // Download missing SVGs.
  let downloaded = 0;
  let cached = 0;
  let failed = 0;
  const surviving = [];
  for (const a of animals) {
    const res = await downloadIfMissing(a.slug, a.codepoint);
    if (res.ok) {
      if (res.cached) cached++;
      else downloaded++;
      surviving.push(a);
    } else {
      failed++;
      console.warn(`  ! ${a.slug} (${a.codepoint}): ${res.error} — omitted from catalog`);
    }
  }
  console.log(`  assets: ${cached} cached, ${downloaded} downloaded, ${failed} failed`);

  const catalog = buildCatalog(surviving);
  console.log('  coverage:');
  reportCoverage(catalog);

  await fs.mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, emitModule(catalog, surviving), 'utf8');
  console.log(`  wrote ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error('catalog build failed:', err);
  process.exit(1);
});
